### ISSUE TITLE
Issues with Instagram pull-up

### ISSUE THREAD

**Issue by i2t4b33e** [galihap76/collector#3]
Can someone help with this?

As i m newbie to linux
Im facing a error while running the cmd python3 main.py -ig ecya.acii
![image](https://user-images.githubusercontent.com/109549991/179583709-0165d1e2-ee34-489a-8514-4f76f7b8cc6b.png)

Traceback (most recent call last):
  File "/collector/main.py", line 321, in <module>
    RUN.Main()
  File "/collector/main.py", line 149, in Main
    L.login(username_read.read(), password_read.read())
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloader.py", line 635, in login
    self.context.login(user, passwd)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 239, in login
    raise ConnectionException("Login: Checkpoint required. Point your browser to "
instaloader.exceptions.ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXG44CaXDMsRkVOZZBO0FaBXRScHvaIIMUkML9oSHlvLCX6yYfDDIVgUgSivjaAboMTIx1Y/AfxKG11WJKh2hziFFRdYIy0b1_d557BttwRh7U-K05p3VUYOpM2uca97C3OGltC2a5q37mHcF_58Vw/ffc_VGKiYGI6eQgsavXVTB3zgeg1zk6YeQSB682c2ZqxNpdUDTAckHTcSN6nV1Pa8Yf0/ - follow the instructions, then retry.

Please help me with this.
Thank You!!

**Comment by galihap76** [comment]
Try to login your browser not from collector. You got same issues [here](https://github.com/instaloader/instaloader/issues/328).

**Comment by galihap76** [comment]
If still not work maybe you need waiting for seconds and run this program again. I think the problem is your instagram account, i try in my account is work fine.

**Comment by i2t4b33e** [comment]
Thanks!! works fine
