### ISSUE TITLE
无法使用呀？每次都是提示安装

### ISSUE THREAD

**Issue by seklure** [galihap76/collector#4]
![image](https://user-images.githubusercontent.com/45745859/179640012-aa6fb5c7-27e4-4d8e-a8af-be9d20c88202.png)

**Comment by galihap76** [comment]
Hi thank for your issues. Hmm if I see again i think you need to update your module and this is because of different requests module installed by the OS and the python dependencies for your local installation.

Try this :
```
sudo python3 -m pip install --upgrade requests
```

**Comment by galihap76** [comment]
I will close as done.
